import type { DateIdea, Profile } from "@/lib/types";

export const currentUser: Profile = {
  id: "you",
  name: "Sloane",
  age: 28,
  location: "Toronto",
  gender: "woman",
  interestedIn: ["men", "women"],
  pronouns: "she/they",
  occupation: "Art director",
  vibe: "Electric but intentional",
  bio: "I like first dates with momentum: live music, tactile classes, strange little bars, and people who are open to the second stop.",
  interests: [
    "live music",
    "night markets",
    "photo walks",
    "vinyl",
    "late-night food",
    "weekend escapes",
  ],
  chemistryNotes: [
    "Lights up around live music and sensory experiences.",
    "Prefers dates that feel like a small story instead of a checklist.",
    "Talks most when the night has a little chaos in it.",
  ],
  avatar: "https://picsum.photos/seed/ycr-you/200/200",
};

export const profilesById: Record<string, Profile> = {
  rio: {
    id: "rio",
    name: "Rio",
    age: 30,
    location: "Toronto",
    gender: "man",
    interestedIn: ["women"],
    pronouns: "he/him",
    occupation: "Motion designer",
    vibe: "Playful extrovert",
    bio: "I say yes to rave basements, rooftop sets, and random side quests if the soundtrack is right.",
    interests: ["drums", "warehouse sets", "street food", "cycling", "sneaker design"],
    chemistryNotes: [
      "Always has one more plan in the chamber.",
      "Most engaged when the energy is loud, social, and a little unplanned.",
    ],
    avatar: "https://picsum.photos/seed/ycr-rio/200/200",
  },
  maeve: {
    id: "maeve",
    name: "Maeve",
    age: 27,
    location: "Toronto",
    gender: "woman",
    interestedIn: ["men", "women"],
    pronouns: "she/her",
    occupation: "Ceramics teacher",
    vibe: "Warm and tactile",
    bio: "I like creative dates, slow drinks, and people who notice details.",
    interests: ["pottery", "natural wine", "interiors", "film photography", "indie playlists"],
    chemistryNotes: [
      "Shows affection through thoughtful planning.",
      "Gets animated when making something with her hands.",
    ],
    avatar: "https://picsum.photos/seed/ycr-maeve/200/200",
  },
  zion: {
    id: "zion",
    name: "Zion",
    age: 29,
    location: "Toronto",
    gender: "other",
    interestedIn: ["women", "other"],
    pronouns: "they/them",
    occupation: "Music journalist",
    vibe: "Sharp and magnetic",
    bio: "Bookstore afternoons and smoky jazz rooms are my native language.",
    interests: ["jazz", "bookstores", "writing", "vinyl", "small concerts"],
    chemistryNotes: [
      "Connects through taste and conversation depth.",
      "Likes dates that shift from browsing to talking without forcing it.",
    ],
    avatar: "https://picsum.photos/seed/ycr-zion/200/200",
  },
  noa: {
    id: "noa",
    name: "Noa",
    age: 31,
    location: "Toronto",
    gender: "woman",
    interestedIn: ["men"],
    pronouns: "she/her",
    occupation: "Product designer",
    vibe: "Calm with a hidden wild streak",
    bio: "Sunrise hikes, architecture walks, and one very good coffee usually beat loud rooms for me.",
    interests: ["hiking", "coffee", "brutalist architecture", "pilates", "travel journals"],
    chemistryNotes: [
      "Prefers momentum that starts calm and opens up later.",
      "Very responsive to curiosity and grounded humor.",
    ],
    avatar: "https://picsum.photos/seed/ycr-noa/200/200",
  },
  cass: {
    id: "cass",
    name: "Cass",
    age: 26,
    location: "Toronto",
    gender: "other",
    interestedIn: ["women", "other", "men"],
    pronouns: "he/they",
    occupation: "Community producer",
    vibe: "Social and sweet",
    bio: "Give me a night market, a camera, and someone who likes wandering more than scheduling.",
    interests: ["photo walks", "night markets", "ramen", "street style", "design fairs"],
    chemistryNotes: [
      "Feels natural in open-ended dates with lots to point at.",
      "Conversation gets stronger while walking side by side.",
    ],
    avatar: "https://picsum.photos/seed/ycr-cass/200/200",
  },
  imani: {
    id: "imani",
    name: "Imani",
    age: 32,
    location: "Toronto",
    gender: "woman",
    interestedIn: ["men", "women"],
    pronouns: "she/her",
    occupation: "Architect",
    vibe: "Grounded and sharp",
    bio: "I like dates with style, strong conversation, and at least one small surprise built in.",
    interests: ["galleries", "design", "cocktails", "city walks", "photography"],
    chemistryNotes: [
      "Responds to visually strong spaces and thoughtful plans.",
      "More likely to click when the date has atmosphere without trying too hard.",
    ],
    avatar: "https://picsum.photos/seed/ycr-imani/200/200",
  },
  miles: {
    id: "miles",
    name: "Miles",
    age: 29,
    location: "Toronto",
    gender: "man",
    interestedIn: ["women"],
    pronouns: "he/him",
    occupation: "Chef",
    vibe: "Warm and curious",
    bio: "Give me a cooking class, a market, or one great low-key bar and I’m fully in.",
    interests: ["cooking", "food crawls", "wine", "comedy", "farmers markets"],
    chemistryNotes: [
      "Likes hands-on dates where conversation happens while doing something.",
      "Food is a stronger signal than pure nightlife.",
    ],
    avatar: "https://picsum.photos/seed/ycr-miles/200/200",
  },
  aria: {
    id: "aria",
    name: "Aria",
    age: 27,
    location: "Toronto",
    gender: "other",
    interestedIn: ["women", "other"],
    pronouns: "she/they",
    occupation: "Playlist editor",
    vibe: "Magnetic and low-key",
    bio: "I tend to like nights with music, rooms with mood, and people who notice details.",
    interests: ["live sets", "indie nights", "vinyl", "zines", "late bars"],
    chemistryNotes: [
      "Connects through music taste and little moments of intensity.",
      "Prefers dates with a little darkness and a strong soundtrack.",
    ],
    avatar: "https://picsum.photos/seed/ycr-aria/200/200",
  },
};

export const candidateProfiles = Object.values(profilesById);

export const profilePersonaNotes: Record<string, string> = {
  rio: "Texts fast, slightly chaotic, playful, and social. Likes teasing, quick pivots, and making plans sound alive instead of polished.",
  maeve: "Texts warmly and thoughtfully. Notices details, asks gentle questions, and sounds grounded rather than performative.",
  zion: "Dry, observant, a little sharp, but still warm when interested. Speaks in specific references and likes conversational tension.",
  noa: "Calm, measured, and low-drama. Replies with clarity, understated humor, and a preference for things that feel easy instead of forced.",
  cass: "Friendly, curious, and visual. Sounds like someone who is already halfway into the wander and pointing things out as they go.",
  imani: "Confident, composed, and design-aware. Slightly flirtier when the other person has taste, never gushy.",
  miles: "Warm, easy, food-literate, and naturally inviting. Sounds like someone who makes people comfortable quickly.",
  aria: "Low-key, specific, a little elusive in a good way. Flirts through music taste, atmosphere, and selective enthusiasm.",
};

export const dateIdeas: DateIdea[] = [
  {
    id: "warehouse-rave",
    title: "Warehouse rave + late-night tacos",
    city: "Toronto",
    category: "High energy",
    image: "https://picsum.photos/seed/ycr-rave/960/1200",
    energy: "High",
    budget: "$$",
    intro: "Industrial lights, a stacked lineup, then one greasy perfect bite at 1:30 AM.",
    whyItWorks:
      "Best for people who flirt through momentum, music, and a second plan after midnight.",
    tags: ["electronic", "dancing", "spontaneous", "late night"],
  },
  {
    id: "vinyl-cocktails",
    title: "Vinyl listening bar + martinis",
    city: "Toronto",
    category: "Taste chemistry",
    image: "https://picsum.photos/seed/ycr-vinyl/960/1200",
    energy: "Medium",
    budget: "$$$",
    intro: "Low light, a deep cut on the speakers, and enough quiet to say something that matters.",
    whyItWorks:
      "Built for people who bond through taste, details, and small pockets of intensity.",
    tags: ["vinyl", "cocktails", "conversation", "music nerds"],
  },
  {
    id: "sunrise-hike",
    title: "Sunrise hike + brutalist coffee run",
    city: "Toronto",
    category: "Soft launch",
    image: "https://picsum.photos/seed/ycr-hike/960/1200",
    energy: "Low",
    budget: "$",
    intro: "Wake up early, trade playlists, then land somewhere with clean concrete and very good espresso.",
    whyItWorks:
      "Great for people who open up slowly and want a date that feels grounded, not performative.",
    tags: ["outdoors", "coffee", "walks", "morning"],
  },
  {
    id: "pottery-wine",
    title: "Pottery wheel class + natural wine",
    city: "Toronto",
    category: "Creative chemistry",
    image: "https://picsum.photos/seed/ycr-pottery/960/1200",
    energy: "Medium",
    budget: "$$",
    intro: "Hands busy, laughs easy, and a glass of orange wine after both bowls collapse.",
    whyItWorks:
      "Ideal for tactile people who want an instant shared memory instead of interview energy.",
    tags: ["creative", "wine", "hands-on", "playful"],
  },
  {
    id: "bookstore-jazz",
    title: "Bookstore browse + basement jazz set",
    city: "Toronto",
    category: "Slow burn",
    image: "https://picsum.photos/seed/ycr-jazz/960/1200",
    energy: "Medium",
    budget: "$$",
    intro: "Trade titles, judge each other's margins, then disappear into a room that smells like brass and old wood.",
    whyItWorks:
      "For pairs that connect through taste, conversation, and a little dramatic atmosphere.",
    tags: ["jazz", "books", "conversation", "culture"],
  },
  {
    id: "night-market",
    title: "Night market photo walk",
    city: "Toronto",
    category: "Wandering",
    image: "https://picsum.photos/seed/ycr-market/960/1200",
    energy: "Medium",
    budget: "$",
    intro: "Street snacks, roaming, and a camera roll full of tiny things you both noticed.",
    whyItWorks:
      "A strong fit for people who click while moving, pointing, and sharing little reactions in real time.",
    tags: ["photo walk", "food", "markets", "explore"],
  },
  {
    id: "gallery-after-dark",
    title: "After-dark gallery + natural wine",
    city: "Toronto",
    category: "Visual chemistry",
    image: "https://picsum.photos/seed/ycr-gallery/960/1200",
    energy: "Medium",
    budget: "$$",
    intro: "A quiet room with strong taste, then one very good glass somewhere nearby.",
    whyItWorks:
      "Best for people who flirt through observation, aesthetics, and slow-building conversation.",
    tags: ["gallery", "wine", "design", "conversation"],
  },
  {
    id: "cooking-class",
    title: "Late cooking class + market dessert stop",
    city: "Toronto",
    category: "Hands-on",
    image: "https://picsum.photos/seed/ycr-cooking/960/1200",
    energy: "Medium",
    budget: "$$",
    intro: "Make something together, laugh when it goes slightly sideways, then keep the night moving with dessert.",
    whyItWorks:
      "Great for people who open up faster when they are doing something together instead of sitting across from each other.",
    tags: ["cooking", "hands-on", "food", "playful"],
  },
  {
    id: "comedy-speakeasy",
    title: "Basement comedy set + speakeasy",
    city: "Toronto",
    category: "Loose and funny",
    image: "https://picsum.photos/seed/ycr-comedy/960/1200",
    energy: "Medium",
    budget: "$$",
    intro: "A little chaos, a dark room, and enough laughter to skip the awkward part.",
    whyItWorks:
      "A strong fit for people who need the pressure lowered before the flirtation gets better.",
    tags: ["comedy", "bar", "humor", "night out"],
  },
  {
    id: "rooftop-cinema",
    title: "Rooftop cinema + midnight noodles",
    city: "Toronto",
    category: "Soft romance",
    image: "https://picsum.photos/seed/ycr-cinema/960/1200",
    energy: "Low",
    budget: "$$",
    intro: "A city view, a shared movie, then noodles while you decide whether the night should keep going.",
    whyItWorks:
      "Ideal for people who like a built-in structure before the conversation opens up after.",
    tags: ["cinema", "city view", "food", "romantic"],
  },
];
